name: 🧪 Test

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{github.event}}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🩺 Run build
              run: pnpm build

            - name: 🩺 Run build:demo
              run: |
                  pnpm build:demo

            - name: Run test
              run: |
                  pnpm exec tsx ./examples-node/src/sheets-node-basic/main.ts

    types:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: Lint
              run: pnpm lint:types

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: Lint
              run: pnpm lint
